name: asmara
channels:
  - conda-forge
dependencies:
  - click
  - hydra-core
  - numpy
  - omegaconf
  - pandas
  - pillow
  - pip
  - python=3.9
  - pytorch
  - pytorch-lightning
  - tensorboard
  - torchvision
  - tqdm
  - holopy
  - pip:
    - matlabengine