seed: 0
data:
  dataset: null
  task: null
  remove: []
  paths: 
    holograms: 'data/processed/holograms'
    inversions: 'data/processed/inversions'
    splits: 'data/processed/splits'
  sample_rate: 0.2
  folds: 
    train: 'train'
    val: 'val'
    test: 'test'
  batch_size: 8
model:
  num_classes: null
  pretrained: False
trainer: 
  accelerator: 'gpu'
  devices: 2
  max_epochs: 10


