seed: 0
data:
  metapath: 'data/processed/meta'
  indoor_dir: 'data/raw/indoor'
  outdoor_dir: 'data/raw/outdoor'
  sample_rate: 0.2
  train_folds: 'train'
  val_folds: 'val'
  test_folds: 'test'
  batch_size: 8
model:
  num_classes: 10
# trainer:

